version: '3.8'

services:
  test-redpanda:
    image: charans97/aggrigator:v4
   # ports:
    #  - "8000:8000"  # Expose port 8080 on the host to port 8080 in the container
#    environment:
 #     - THROUGHPUT=250
  #    - BOOTSTRAP_SERVERS=localhost:9092
    # Optionally, you can also set volume mounts, networks, etc.
    volumes:
      - ./:/app/configs
    networks:
      - redpanda-quickstart-one-broker_redpanda_network

networks:
  redpanda-quickstart-one-broker_redpanda_network:
    external: true
